### ISSUE TITLE
fun build时报错"spawn mvn ENOENT"

### ISSUE THREAD

**Issue by end1314** [vangie/oversize-java-example#2]
使用fun build打包时发生错误,如下:
using template: template.yml
start building function dependencies without docker

building nas-example/oversize-java-example

running task flow MavenTaskFlow
running task: MavenCompileTask
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn mvn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
看问题像是mvn打包的问题,于是我添加maven环境变量
mvn -version
正常显示
但继续执行时依然报以上错误

**Comment by end1314** [comment]
已在官方项目下
https://github.com/alibaba/funcraft/issues/878#issue-603745452
回复
